/* Warning, this is a very basic generator with a lot of approximation 
input data : [HBFBGA, NAC, 19x19x2.71mm, 528, , A, C04-25469A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([19.0,19.0,2.71], center=false);
