/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, QCB, 4.5x3x0.9mm, 14, , A, C04-21362A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.5,3.0,0.9], center=false);
