/* Warning, this is a very basic generator with a lot of approximation 
input data : [SOT-23, CZX, 2.80x1.60mm, 6, , D, C04-00028D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.8,1.6,1.0], center=false);
