/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, TCC, 12x14x1.76mm, 621, , A, C04-25690A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,14.0,1.76], center=false);
