/* Warning, this is a very basic generator with a lot of approximation 
input data : [VSOP, QJX, 8x13.4mm, 28, , C, C04-00075C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,13.4,1.0], center=false);
