/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, AHB, 12x12x1.3mm, 180, , A, C04-21120A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,12.0,1.3], center=false);
