/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, ABA, 9x9x1.38mm, 100, , A, C04-01067A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.0,9.0,1.38], center=false);
