/* Warning, this is a very basic generator with a lot of approximation 
input data : [HB2FBGA, H5C, 23x30x3.80mm, 767, , A, C04-25653A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([23.0,30.0,3.8], center=false);
