/* Warning, this is a very basic generator with a lot of approximation 
input data : [WFBGA, 2MX, 4x6x0.73mm, 34, , A, C04-00164A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,6.0,0.73], center=false);
