/* Warning, this is a very basic generator with a lot of approximation 
input data : [SOT-223, N7X, 6.50x3.50mm, 5, , E, C04-00137E]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.5,3.5,1.0], center=false);
