/* Warning, this is a very basic generator with a lot of approximation 
input data : [MQFP, VCX, 14x14x2.7mm, 64, , B, C04-00022B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,14.0,2.7], center=false);
