/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, GJB, 3.593x3.513mm, 64, , A, C04-21531A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.593,3.513,1.0], center=false);
