/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, EHB, 0.825x1.111x0.538mm, 4, , A, C04-21207A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([0.825,1.111,0.538], center=false);
