/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, P6A, 4x4x0.9mm, 32, , A, C04-01115A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,0.9], center=false);
