/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, H4A, 3.2x2.5x0.9mm, 4, , B, C04-01006B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.2,2.5,0.9], center=false);
