/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 4MX, 3x3x0.9mm, 16, , A, C04-00508A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,3.0,0.9], center=false);
