/* Warning, this is a very basic generator with a lot of approximation 
input data : [UFBGA, BVB, 6x6x0.6mm, 88, , A, C04-21158A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,0.6], center=false);
