/* Warning, this is a very basic generator with a lot of approximation 
input data : [VSFN, LYB, 4x2x0.9mm, 2, , D, C04-21315D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,2.0,0.9], center=false);
