/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, APB, 15x15x1.25mm, 256, , A, C04-21125A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([15.0,15.0,1.25], center=false);
