/* Warning, this is a very basic generator with a lot of approximation 
input data : [BFBGA, BWC, 23x23x3.23mm, 773, , A, C04-25198A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([23.0,23.0,3.23], center=false);
