/* Warning, this is a very basic generator with a lot of approximation 
input data : [MQFP, TWX, 10x10x2mm, 44, , C, C04-00071C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,2.0], center=false);
