/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, EMB, 0.848x1.287x0.39mm, 4, , A, C04-21211A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([0.848,1.287,0.39], center=false);
