/* Warning, this is a very basic generator with a lot of approximation 
input data : [QFN, 2HC, 12x12x0.85mm, 135, , A, C04-25006A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,12.0,0.85], center=false);
