/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, HPB, 4x5x1mm, 28, , B, C04-21564B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,5.0,1.0], center=false);
