/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, 6YX, 20.5x25.4mm, 52, , B, C04-10050B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([20.5,25.4,1.0], center=false);
