/* Warning, this is a very basic generator with a lot of approximation 
input data : [BBGA, BPC, 40x40x3.22mm, 1517, , A, C04-25190A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([40.0,40.0,3.22], center=false);
