/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, JDA, 2x2x0.9mm, 6, , A, C04-01016A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.9], center=false);
