/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, FMA, 1.2x0.8x0.575mm, 6, , B, C04-01188B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 22 13:34:48 CET 2026
*/
D1=1.2;
E1=0.8;
A=0.575;
LINE1="M PIC32";
LINE2="XXXXXX";
LINE3="XXXXXX";
LINE4="IIIIII";
LINE5="YYWWNNN";

//body
    module C04_01188B(      LINE1="M PIC32",
			LINE2="CPNCPN",
			LINE3="CPNCPN",
			LINE4="IIIIII",
			LINE5="YYWWNNN")
{
color("black")
translate([0,0,0])
cube([1.2,0.8,0.575], center=false); 
	color("white")
	scale([1,1,0.1])
	translate([D1/2,E1-1*E1/7,A*10+0.5]) 
	     linear_extrude(height = 3, center = true, convexity = 10, twist = 0) 
	{
        translate([0.3-D1/2,0,0])
      text(".", size=0.5142857142857142, font="Liberation Serif",  valign ="left", halign ="left");
     
      translate([0,-1*E1/7,0]) 
	text(LINE1, size=0.9*E1/7, font="Liberation Serif",  valign ="left", halign ="center");

   translate([0,-2*E1/7,0]) 
	text(LINE2, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
 translate([0,-3*E1/7,0]) 
	text(LINE3, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
   translate([0,-4*E1/7,0]) 
	text(LINE4, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");  
   translate([0,-5*E1/7,0]) 
	text(LINE5, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");     
	}
  
  }
 
      if(demo==undef)
          
      	C04_01188B();

