/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, KDC, 8x8x0.9mm, 56, , D, C04-25526D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,8.0,0.9], center=false);
