/* Warning, this is a very basic generator with a lot of approximation 
input data : [BFBGA, 6VC, 31x31x3.38mm, 1330, , A, C04-25077A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([31.0,31.0,3.38], center=false);
