/* Warning, this is a very basic generator with a lot of approximation 
input data : [HB2BGA, 9AW, 45x45x4.28mm, 1932, , B, C04-00636B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([45.0,45.0,4.28], center=false);
