/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, NBA, 3x3x0.9mm, 16, , A, C04-01284A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,3.0,0.9], center=false);
