/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, FSB, 2.944x2.699x0.483mm, 45, , A, C04-21247A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.944,2.699,0.483], center=false);
