/* Warning, this is a very basic generator with a lot of approximation 
input data : [PQFP, KLB, 14x20x2.8mm, 100, , B, C04-21293B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,20.0,2.8], center=false);
