/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, L9C, 5x6x1mm, 8, , B, C04-25657B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,6.0,1.0], center=false);
