/* Warning, this is a very basic generator with a lot of approximation 
input data : [PLCC, , 11.5x11.5x4.4mm, 28, , E, C04-00026E]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.5,11.5,4.4], center=false);
