/* Warning, this is a very basic generator with a lot of approximation 
input data : [VGQFN, PSX, 9x9x0.927mm, 64, , D, C04-00530D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.0,9.0,0.927], center=false);
