/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFBGA, 3MX, 5.5x5.5x0.9mm, 82, , A, C04-00463A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.5,5.5,0.9], center=false);
