/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, 6JX, 11x11x1.56mm, 169, , C, C04-00439C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,1.56], center=false);
