/* Warning, this is a very basic generator with a lot of approximation 
input data : [TSOT, L9X, 2.90x1.60mm, 5, , D, C04-00128D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.9,1.6,1.0], center=false);
