/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, SYB, 7x7x1mm, 32, , B, C04-21422B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,7.0,1.0], center=false);
