/* Warning, this is a very basic generator with a lot of approximation 
input data : [FCBGA, THX, 11x11mm, 169, , A, C04-00309A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,1.0], center=false);
