/* Warning, this is a very basic generator with a lot of approximation 
input data : [TQFN, 9DW, 5x5x1.05mm, 32, , A, C04-00681A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,5.0,1.05], center=false);
