/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, ARB, 15x15x1.4mm, 289, , B, C04-21127B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([15.0,15.0,1.4], center=false);
