/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, LLC, 14.5x11x1.44mm, 325, , B, C04-25656B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.5,11.0,1.44], center=false);
