/* Warning, this is a very basic generator with a lot of approximation 
input data : [SC70, R5X, 2.10x1.25mm, 6, , C, C04-00151C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.1,1.25,1.0], center=false);
