/* Warning, this is a very basic generator with a lot of approximation 
input data : [LQFP, PPX, 7x7x1.4mm, 32, , B, C04-00045B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/
D1=7.0;
E1=7.0;
A=1.4;

//body
color("black")
translate([0,0,0])
cube([D1,E1,A], center=false);



//if(is_string(CPN1))
{
    LINE2="XXXXXX";
}
//if(CPN2==undef)
{
    LINE3="XXXXXX";
}
    LINE4="ARM";
//if(DATECODE==undef)
    {
    LINE5="YYWWNNN";
}
//if(LOGO==undef)
    {
    LINE1="M PIC32";
}

color("white")
 translate([D1/2,E1-1*E1/7,0.5+A-0.9]) 
 {
        translate([0.5-D1/2,0,0])
      text(".", size=3, font="Liberation Serif",  valign ="left", halign ="left");
     
      translate([0,-1*E1/7,0]) 
 text(LINE1, size=0.9*E1/7, font="Liberation Serif",  valign ="left", halign ="center");

 translate([0,-2*E1/7,0]) 
 text(LINE2, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
 translate([0,-3*E1/7,0]) 
 text(LINE3, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
   translate([0,-4*E1/7,0]) 
 text(LINE4, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");  
   translate([0,-5*E1/7,0]) 
 text(LINE5, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");     
}
  
 
 
 
