/* Warning, this is a very basic generator with a lot of approximation 
input data : [TSOP, W9X, 12x20mm, 48, , B, C04-00177B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,20.0,1.0], center=false);
