/* Warning, this is a very basic generator with a lot of approximation 
input data : [PQFP OR MQFP, KXB, 28x28x3.37mm, 208, , A, C04-21300A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([28.0,28.0,3.37], center=false);
