/* Warning, this is a very basic generator with a lot of approximation 
input data : [VTLA, 6SX, 6x6x0.9mm, 44, , D, C04-00157D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,0.9], center=false);
