/* Warning, this is a very basic generator with a lot of approximation 
input data : [UQFN, MDA, 1x1x0.6mm, 6, , A, C04-01045A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.0,1.0,0.6], center=false);
