/* Warning, this is a very basic generator with a lot of approximation 
input data : [LQFP, 2QB, 14x20x1.4mm, 128, , B, C04-21009B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,20.0,1.4], center=false);
