/* Warning, this is a very basic generator with a lot of approximation 
input data : [WDFN, QEB, 2x3x0.8mm, 8, , A, C04-21364A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,3.0,0.8], center=false);
