/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, B8B, 10x10x1.2mm, 121, , A, C04-21139A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,1.2], center=false);
