/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 2JC, 12x12x0.85mm, 138, , A, C04-25007A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,12.0,0.85], center=false);
