/* Warning, this is a very basic generator with a lot of approximation 
input data : [FCCSP, D6, 13.20x8.90x2.30mm, 208, , A, C04-25522A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([13.2,8.9,2.3], center=false);
