/* Warning, this is a very basic generator with a lot of approximation 
input data : [UQFN, QMX, 02x02x0.55mm, 12, , A, C04-00247A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.55], center=false);
