/* Warning, this is a very basic generator with a lot of approximation 
input data : [PBGA, ACA, 19x19x2.36mm, 289, , A, C04-01087A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([19.0,19.0,2.36], center=false);
