/* Warning, this is a very basic generator with a lot of approximation 
input data : [QDPAK, 7UW, 15x15.4x2.30mm, 22, , A, C04-00650A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([15.0,15.4,2.3], center=false);
