/* Warning, this is a very basic generator with a lot of approximation 
input data : [BGA, N7C, 31x31x2.24mm, 896, , A, C04-25466A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([31.0,31.0,2.24], center=false);
