/* Warning, this is a very basic generator with a lot of approximation 
input data : [WFBGA, SZX, 9x9x0.8mm, 144, , B, C04-00380B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.0,9.0,0.8], center=false);
