/* Warning, this is a very basic generator with a lot of approximation 
input data : [PLCC, KBB, 19.1x19.1x4.4mm, 52, , A, C04-21289A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([19.1,19.1,4.4], center=false);
