/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFLGA, ATA, 2.0x1.6mm, 6, , A, C04-01201A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,1.6,1.0], center=false);
