/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 5NX, 6x6x1.0mm, 28, , E, C04-00401E]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,1.0], center=false);
