/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, MNA, 10x10x0.9mm, 72, , A, C04-01093A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,0.9], center=false);
