/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFLGA, 4NW, 10x10x0.81mm, 88, , B, C04-00593B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,0.81], center=false);
