/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 2NW, 14x14x0.9mm, 180, , A, C04-00548A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,14.0,0.9], center=false);
