/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, 6GC, 27x27x2.28mm, 1069, , A, C04-25064A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([27.0,27.0,2.28], center=false);
