/* Warning, this is a very basic generator with a lot of approximation 
input data : [HBBGA, NMC, 40x40x3.23mm, 1503, , A, C04-25480A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([40.0,40.0,3.23], center=false);
