/* Warning, this is a very basic generator with a lot of approximation 
input data : [UPDFN, 9FW, 2x2x0.6mm, 6, , C, C04-00683C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.6], center=false);
