/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, 6TW, 19x25x2.6mm, 82, , G, C04-00633G]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([19.0,25.0,2.6], center=false);
