/* Warning, this is a very basic generator with a lot of approximation 
input data : [HB1BGA, SRC, 33x33x3.9mm, 1292, , A, C04-25679A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([33.0,33.0,3.9], center=false);
