/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, NVX, 10x10x0.9mm, 132, , A, C04-00472A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,0.9], center=false);
