/* Warning, this is a very basic generator with a lot of approximation 
input data : [CONTACT, LAB, 2.5x6.5x0.5mm, 3, , A, C04-21303A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.5,6.5,0.5], center=false);
