/* Warning, this is a very basic generator with a lot of approximation 
input data : [UQFN, 3VX, 1.6x2.1x0.55mm, 10, , A, C04-00379A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.6,2.1,0.55], center=false);
