/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, 9UX, 6x5x0.9mm, 8, , A, C04-00413A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,5.0,0.9], center=false);
