/* Warning, this is a very basic generator with a lot of approximation 
input data : [FCBGA, 5CC, 25x25x2.56mm, 888, , B, C04-25057B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([25.0,25.0,2.56], center=false);
