/* Warning, this is a very basic generator with a lot of approximation 
input data : [B1BGA, NLC, 27x27x2.80mm, 672, , A, C04-25479A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([27.0,27.0,2.8], center=false);
