/* Warning, this is a very basic generator with a lot of approximation 
input data : [LQFP, 2HB, 14x14x1.4mm, 120, , A, C04-21005A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,14.0,1.4], center=false);
