/* Warning, this is a very basic generator with a lot of approximation 
input data : [FCCSP, CZC, 22.80x8.90x2.30mm, 352, , B, C04-25517B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([22.8,8.9,2.3], center=false);
