/* Warning, this is a very basic generator with a lot of approximation 
input data : [MQFP, KGC, 14x20x2.72mm, 100, , A, C04-25364A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,20.0,2.72], center=false);
