/* Warning, this is a very basic generator with a lot of approximation 
input data : [TSSOP, NRB, 4.4x9.7x1mm, 28, , A, C04-21347A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.4,9.7,1.0], center=false);
