/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, 6RW, 10x10x1.5mm, 144, , B, C04-00631B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,1.5], center=false);
