/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, ZSX, 15.5x20.7mm, 39, , C, C04-10052C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([15.5,20.7,1.0], center=false);
