/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFBGA, 3MX, 5.5x5.5x0.9mm, 82, , A, C04-00463A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 22 13:34:47 CET 2026
*/
D1=5.5;
E1=5.5;
A=0.9;
LINE1="M PIC32";
LINE2="XXXXXX";
LINE3="XXXXXX";
LINE4="IIIIII";
LINE5="YYWWNNN";

//body
    module C04_00463A(      LINE1="M PIC32",
			LINE2="CPNCPN",
			LINE3="CPNCPN",
			LINE4="IIIIII",
			LINE5="YYWWNNN")
{
color("black")
translate([0,0,0])
cube([5.5,5.5,0.9], center=false); 
	color("white")
	scale([1,1,0.1])
	translate([D1/2,E1-1*E1/7,A*10+0.5]) 
	     linear_extrude(height = 3, center = true, convexity = 10, twist = 0) 
	{
        translate([0.3-D1/2,0,0])
      text(".", size=2.357142857142857, font="Liberation Serif",  valign ="left", halign ="left");
     
      translate([0,-1*E1/7,0]) 
	text(LINE1, size=0.9*E1/7, font="Liberation Serif",  valign ="left", halign ="center");

   translate([0,-2*E1/7,0]) 
	text(LINE2, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
 translate([0,-3*E1/7,0]) 
	text(LINE3, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
   translate([0,-4*E1/7,0]) 
	text(LINE4, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");  
   translate([0,-5*E1/7,0]) 
	text(LINE5, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");     
	}
  
  }
 
      if(demo==undef)
          
      	C04_00463A();

