/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, H7A, 3.2x5.0x0.9mm, 6, , A, C04-01009A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.2,5.0,0.9], center=false);
