/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, HGA, 1.2x1.6x0.6mm, 4, , A, C04-01152A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.2,1.6,0.6], center=false);
