/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, LUX, 12x12x1.19mm, 144, , A, C04-00511A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,12.0,1.19], center=false);
