/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, K4A, 6x5x0.9mm, 11, , A, C04-01197A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,5.0,0.9], center=false);
