/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 8GW, 9x9x1.2mm, 289, , A, C04-00661A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.0,9.0,1.2], center=false);
