/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, FZB, 3.444x3.17x0.483mm, 56, , A, C04-21254A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.444,3.17,0.483], center=false);
