/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, Q3X, 2x3x0.6mm, 8, , C, C04-00203C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,3.0,0.6], center=false);
