/* Warning, this is a very basic generator with a lot of approximation 
input data : [BGA, AUC, 29x29x2.21mm, 780, , A, C04-25172A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([29.0,29.0,2.21], center=false);
