/* Warning, this is a very basic generator with a lot of approximation 
input data : [TSB, 3UB, 2.0x2.5x0.55mm, 2, , A, C04-21472A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.5,0.55], center=false);
