/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 6NX, 4x4x1.0mm, 20, , C, C04-00402C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,1.0], center=false);
