/* Warning, this is a very basic generator with a lot of approximation 
input data : [WQFN, 4FW, 3x3x0.75mm, 20, , A, C04-00585A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,3.0,0.75], center=false);
