/* Warning, this is a very basic generator with a lot of approximation 
input data : [B1QFN, M4A, 8x8x3mm, 52, , C, C04-01055C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,8.0,3.0], center=false);
