/* Warning, this is a very basic generator with a lot of approximation 
input data : [VLGA, AUA, 2.5x2.0x0.89mm, 4, , B, C04-01202B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.5,2.0,0.89], center=false);
