/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, KWX, 9x9x1.2mm, 105, , A, C04-00469A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.0,9.0,1.2], center=false);
