/* Warning, this is a very basic generator with a lot of approximation 
input data : [TQFP, R9X, 16x1 6x 1mm, 144, , B, C04-00155B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([16.0,16.0,1.0], center=false);
