/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, ZWX, 6x6x0.9mm, 48, , C, C04-00531C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,0.9], center=false);
