/* Warning, this is a very basic generator with a lot of approximation 
input data : [QFN, M8A, 2.5x3.0x1.85mm, 20, , A, C04-01054A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.5,3.0,1.85], center=false);
