/* Warning, this is a very basic generator with a lot of approximation 
input data : [LBGA, JHC, 10x10x1.47mm, 81, , B, C04-25340B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,1.47], center=false);
