/* Warning, this is a very basic generator with a lot of approximation 
input data : [PDFN, ESX, 3.3x3.3x0.9mm, 8, , A, C04-00195A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.3,3.3,0.9], center=false);
