/* Warning, this is a very basic generator with a lot of approximation 
input data : [XBGA (TFBGA), 2XX, 10x10x1.10mm, 121, , F, C04-00148F]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,1.1], center=false);
