/* Warning, this is a very basic generator with a lot of approximation 
input data : [DFN, CJX, 3x3mm, 8, , C, C04-00062C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,3.0,1.0], center=false);
