/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, NDA, 1.2x2.0x0.9mm, 10, , B, C04-01029B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.2,2.0,0.9], center=false);
