/* Warning, this is a very basic generator with a lot of approximation 
input data : [X2DFN, K6A, 1.2x1.2x0.4mm, 6, , A, C04-01259A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.2,1.2,0.4], center=false);
