/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, J5A, 2.0x2.5mm, 4, , B, C04-01004B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.5,1.0], center=false);
