/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 6MW, 3x2x0.9mm, 12, , C, C04-00626C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,2.0,0.9], center=false);
