/* Warning, this is a very basic generator with a lot of approximation 
input data : [TDFN, HAA, 3.5x3.0x1.15mm, 14, , A, C04-01062A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.5,3.0,1.15], center=false);
