/* Warning, this is a very basic generator with a lot of approximation 
input data : [PBGA, QYC, 23x23x2.44mm, 484, , A, C04-25590A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([23.0,23.0,2.44], center=false);
