/* Warning, this is a very basic generator with a lot of approximation 
input data : [SSOP, E6A, 15.8x7.6mm, 48, , A, C04-01148A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([15.8,7.6,1.0], center=false);
