/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, GFB, 2.78x2.578x0.4mm, 35, , A, C04-21492A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.78,2.578,0.4], center=false);
