/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, VWX, 8x8x0.9mm, 56, , A, C04-00352A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,8.0,0.9], center=false);
