/* Warning, this is a very basic generator with a lot of approximation 
input data : [CDFP, E7C, 2x1.2mm, 2, , A, C04-25527A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,1.2,1.0], center=false);
