/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, J9A, 2.5x2.5x0.9mm, 10, , A, C04-01018A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.5,2.5,0.9], center=false);
