/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, HBA, 0.85x0.85x0.6mm, 4, , A, C04-01043A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([0.85,0.85,0.6], center=false);
