/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, BAB, 11x11x1.2mm, 196, , A, C04-21141A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,1.2], center=false);
