/* Warning, this is a very basic generator with a lot of approximation 
input data : [TSOT, NMB, 1.6x2.9x1.1mm, 5, , B, C04-21344B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.6,2.9,1.1], center=false);
