/* Warning, this is a very basic generator with a lot of approximation 
input data : [WDFN, K5A, 3x2x0.8mm, 14, , A, C04-01065A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,2.0,0.8], center=false);
