/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, D8C, 11x11x1.42mm, 169, , D, C04-25535D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,1.42], center=false);
