/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, HKA, 1.6x1.6x0.6mm, 6, , A, C04-01154A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.6,1.6,0.6], center=false);
