/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, BGC, 27x272.17mm, 1071, , A, C04-25065A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([27.0,272.17,1.0], center=false);
