/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 3LW, 4x4x1.0mm, 28, , B, C04-00565B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,1.0], center=false);
