/* Warning, this is a very basic generator with a lot of approximation 
input data : [X2SON, X9X, 1.5x15.x0.4mm, 6, , A, C04-00215A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.5,15.0,0.4], center=false);
