/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, QGA, 7x11x0.9mm, 60, , A, C04-01276A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,11.0,0.9], center=false);
