/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, BUC, 23x23x2.17mm, 773, , A, C04-25196A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([23.0,23.0,2.17], center=false);
