/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, AYB, 8x8x1.05mm, 256, , A, C04-21133A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,8.0,1.05], center=false);
