/* Warning, this is a very basic generator with a lot of approximation 
input data : [UFBGA, C6B, 10x5x0.6mm, 162, , A, C04-21167A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,5.0,0.6], center=false);
