/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, QAB, 3x4x1mm, 14, , A, C04-21360A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,4.0,1.0], center=false);
