/* Warning, this is a very basic generator with a lot of approximation 
input data : [QFN, QRA, 4.5x3x1.9mm, 24, , A, C04-01295A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.5,3.0,1.9], center=false);
