/* Warning, this is a very basic generator with a lot of approximation 
input data : [LBGA, HWC, 25x25x1.70mm, 955, , A, C04-25661A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([25.0,25.0,1.7], center=false);
