/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, 3VW, 2x2x0.55mm, 10, , A, C04-00574A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.55], center=false);
