/* Warning, this is a very basic generator with a lot of approximation 
input data : [UQFN, MQX, 6x6x0.5mm, 28, , C, C04-00209C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,0.5], center=false);
