/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, NFC, 17x17x1.73mm, 728, , A, C04-25536A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([17.0,17.0,1.73], center=false);
