/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, UVX, 5x6.5x0.9mm, 49, , B, C04-00358B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,6.5,0.9], center=false);
