/* Warning, this is a very basic generator with a lot of approximation 
input data : [LBGA, 6BC, 11x11x1.7mm, 100, , A, C04-25059A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,1.7], center=false);
