/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, YXX, 10x10x1.0mm, 72, , B, C04-00454B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,1.0], center=false);
