/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, QKA, 6x11x0.9mm, 56, , A, C04-01282A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,11.0,0.9], center=false);
