/* Warning, this is a very basic generator with a lot of approximation 
input data : [FLATPACK, 8GB, 12.2x20.8x3.05mm, 32, , A, C04-21099A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.2,20.8,3.05], center=false);
