/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, ZRX, 13.4X18.7x2.8mm, 30, , B, C04-10051B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([13.4,18.7,2.8], center=false);
