/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, TDB, 9x9x1mm, 64, , A, C04-21434A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.0,9.0,1.0], center=false);
