/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, QWB, 8.5x6.0x1.0mm, 24, , C, C04-21554C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.5,6.0,1.0], center=false);
