/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, HVX, 12x12x1.4mm, 196, , A, C04-00237A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,12.0,1.4], center=false);
