/* Warning, this is a very basic generator with a lot of approximation 
input data : [WQFN, 2PX, 3x3x0.8mm, 12, , A, C04-00302A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,3.0,0.8], center=false);
