/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, A7B, 10x10x1.37mm, 247, , A, C04-21115A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,1.37], center=false);
