/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, V8X, 2x2x1.0mm, 8, , D, C04-00198D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,1.0], center=false);
