/* Warning, this is a very basic generator with a lot of approximation 
input data : [QFN-S, MCX, 6x6mm, 28, , C, C04-00124C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,1.0], center=false);
