/* Warning, this is a very basic generator with a lot of approximation 
input data : [MQFP, AWC, 14x14x2.15mm, 80, , A, C04-25173A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,14.0,2.15], center=false);
