/* Warning, this is a very basic generator with a lot of approximation 
input data : [FLATPACK, 8FB, 10.2x18.3x3.02mm, 28, , A, C04-21098A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.2,18.3,3.02], center=false);
