/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 4TB, 16x16x1.23mm, 243, , B, C04-21556B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([16.0,16.0,1.23], center=false);
