/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 7GW, 8x5x1mm, 60, , A, C04-00646A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,5.0,1.0], center=false);
