/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, NCC, 10x10x2.25mm, 170, , A, C04-25470A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,2.25], center=false);
