/* Warning, this is a very basic generator with a lot of approximation 
input data : [MSOP, EMX, 3x3mm, 10, , F, C04-00021F]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,3.0,1.0], center=false);
