/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 8YW, 6x7x1mm, 39, , A, C04-00677A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,7.0,1.0], center=false);
