/* Warning, this is a very basic generator with a lot of approximation 
input data : [TSOP_TYPE_I, NLB, 8x18.4x1mm, 32, , A, C04-21343A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,18.4,1.0], center=false);
