/* Warning, this is a very basic generator with a lot of approximation 
input data : [TRANSPDR, DJB, 12.1x5.9x3.1mm, , , B, C04-21190B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.1,5.9,3.1], center=false);
