/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, 4YX, 12.7x11mm, 25, , A, C04-00487A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.7,11.0,1.0], center=false);
