/* Warning, this is a very basic generator with a lot of approximation 
input data : [XFLGA, 3UX, 4x6x0.6mm, 48, , A, C04-00163A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,6.0,0.6], center=false);
