/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, NPA, 5.0x6.5mm, 40, , A, C04-01206A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,6.5,1.0], center=false);
