/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, HFX, 11x11x1.4mm, 169, , B, C04-00365B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,1.4], center=false);
