/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, SMX, 2x1.6x0.9mm, 4, , A, C04-00486A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,1.6,0.9], center=false);
