/* Warning, this is a very basic generator with a lot of approximation 
input data : [PLCC, XPX, 29.3x29.3x4.4mm, 84, , C, C04-00093C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([29.3,29.3,4.4], center=false);
