/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, M2C, 4x6x1mm, 36, , A, C04-25399A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,6.0,1.0], center=false);
