/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, SNC, 27x27x2.315mm, 1285, , B, C04-25655B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([27.0,27.0,2.315], center=false);
