/* Warning, this is a very basic generator with a lot of approximation 
input data : [MQFN, 3CX, 5x5x1.0mm, 20, , B, C04-00186B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,5.0,1.0], center=false);
