/* Warning, this is a very basic generator with a lot of approximation 
input data : [BBGA, 7KC, 45x45x4.0mm, 1932, , C, C04-25091C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([45.0,45.0,4.0], center=false);
