/* Warning, this is a very basic generator with a lot of approximation 
input data : [LGA, 8FW, 5.8x4.9x1.71mm, 22, , B, C04-00660B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.8,4.9,1.71], center=false);
