/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 2PW, 4x4x1.2mm, 16, , B, C04-00549B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,1.2], center=false);
