/* Warning, this is a very basic generator with a lot of approximation 
input data : [SOT-23, N6B, 1.6x2.9x1.3mm, 6, , A, C04-21333A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.6,2.9,1.3], center=false);
