/* Warning, this is a very basic generator with a lot of approximation 
input data : [XDFN, D5B, 1.8x2.2x0.4mm, 8, , A, C04-21186A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.8,2.2,0.4], center=false);
