/* Warning, this is a very basic generator with a lot of approximation 
input data : [X2QFN, 9XX, 1.5x1.5x0.40mm, 10, , A, C04-00376A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.5,1.5,0.4], center=false);
