/* Warning, this is a very basic generator with a lot of approximation 
input data : [QFN, TRX, 8x8x1.0mm, 44, , D, C04-00103D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,8.0,1.0], center=false);
