/* Warning, this is a very basic generator with a lot of approximation 
input data : [UFBGA, C5B, 9.5x7x0.65mm, 117, , A, C04-21166A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.5,7.0,0.65], center=false);
