/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, GXB, 1.094x1.464x0.39mm, 4, , A, C04-21495A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.094,1.464,0.39], center=false);
