/* Warning, this is a very basic generator with a lot of approximation 
input data : [HFCBGA, 4BC, 27x27mm, 672, , A, C04-25039A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([27.0,27.0,1.0], center=false);
