/* Warning, this is a very basic generator with a lot of approximation 
input data : [PQFP, T7X, 10x10x2mm, 44, , A, C04-00119A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,2.0], center=false);
