/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, 6XW, 2x2x0.9mm, 8, , B, C04-00637B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.9], center=false);
