/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, LSX, 6x6x0.9mm, 44, , B, C04-17043B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,0.9], center=false);
