/* Warning, this is a very basic generator with a lot of approximation 
input data : [TBGA, 4DX, 6x8x1.2mm, 24, , B, C04-00199B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,8.0,1.2], center=false);
