/* Warning, this is a very basic generator with a lot of approximation 
input data : [TRANSPDR, 7ZW, 12x5.8x3.1mm, , , A, C04-00657A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,5.8,3.1], center=false);
