/* Warning, this is a very basic generator with a lot of approximation 
input data : [CLCC, F6C, .250x.250x.075In., 16, , A, C04-25637A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.35,6.35,1.9049999999999998], center=false);
