/* Warning, this is a very basic generator with a lot of approximation 
input data : [SOT-23, CVX, 2.90x1.30mm, 3, , C, C04-00104C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.9,1.3,1.0], center=false);
