/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFBGA, 2HW, 5.5x5.5x0.92mm, 64, , B, C04-00543B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.5,5.5,0.92], center=false);
