/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, QRB, 6.5x3x0.9mm, 26, , B, C04-21459B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.5,3.0,0.9], center=false);
