/* Warning, this is a very basic generator with a lot of approximation 
input data : [SOT-89, BTX, 4.50x2.21mm, 3, , E, C04-00029E]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.5,2.21,1.0], center=false);
