/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, AXB, 4x4x1.11mm, 40, , A, C04-21132A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,1.11], center=false);
