/* Warning, this is a very basic generator with a lot of approximation 
input data : [PQFP, U7X, 20x14x3.4mm, 80, , A, C04-00280A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([20.0,14.0,3.4], center=false);
