/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 5LX, 9x9x1.0mm, 64, , F, C04-00483F]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.0,9.0,1.0], center=false);
