/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, HXX, 14x14x1.14mm, 323, , A, C04-00245A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,14.0,1.14], center=false);
