/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, RRB, 5x5x0.9mm, 20, , A, C04-21498A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,5.0,0.9], center=false);
