/* Warning, this is a very basic generator with a lot of approximation 
input data : [UQFN, MVX, 2.5x2.5x0.6mm, 16, , A, C04-00216A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.5,2.5,0.6], center=false);
