/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, 2XW, 15.5x20.7x2.8mm, 39, , B, C04-10054B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([15.5,20.7,2.8], center=false);
