/* Warning, this is a very basic generator with a lot of approximation 
input data : [WFBGA, 7UX, 6x6x0.8mm, 64, , A, C04-00408A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,0.8], center=false);
