/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, K3C, 8x8x1.0mm, 56, , A, C04-25665A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,8.0,1.0], center=false);
