/* Warning, this is a very basic generator with a lot of approximation 
input data : [X2SON, X8X, 2x2x0.4mm, 8, , A, C04-00201A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.4], center=false);
