/* Warning, this is a very basic generator with a lot of approximation 
input data : [USON, UAX, 2x2x0.55mm, 8, , A, C04-00200A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.55], center=false);
