/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, 3WB, 2.199x2.215x0.483mm, 27, , C, C04-21517C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.199,2.215,0.483], center=false);
