/* Warning, this is a very basic generator with a lot of approximation 
input data : [MFPF, 3YB, 19x13.44x2.78mm, 48, , C, C04-21543C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([19.0,13.44,2.78], center=false);
