/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, LSB, 25x20x0.70mm, 42, , A, C04-21454A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([25.0,20.0,0.7], center=false);
