/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, AFA, 13x13x1.2mm, 168, , B, C04-01191B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([13.0,13.0,1.2], center=false);
