/* Warning, this is a very basic generator with a lot of approximation 
input data : [BBGA, CPC, 23x23x3.32mm, 480, , A, C04-25215A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([23.0,23.0,3.32], center=false);
