/* Warning, this is a very basic generator with a lot of approximation 
input data : [FCCSP, 4JC, 10x10mm, 69, , A, C04-25043A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,1.0], center=false);
