/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, 5XC, 4x3x1.0mm, 10, , A, C04-25461A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,3.0,1.0], center=false);
