/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, NRC, 9.3x5.8x0.345mm, , , A, C04-25484A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.3,5.8,0.345], center=false);
