/* Warning, this is a very basic generator with a lot of approximation 
input data : [FCCSP, 3HW, 14x14x1.78mm, 256, , B, C04-00563B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,14.0,1.78], center=false);
