/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, LFB, 21.72x14.73x2.113mm, 28, , B, C04-21305B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([21.72,14.73,2.113], center=false);
