/* Warning, this is a very basic generator with a lot of approximation 
input data : [BFBGA, 6WC, 31x31x2.83mm, 1408, , A, C04-25078A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([31.0,31.0,2.83], center=false);
