/* Warning, this is a very basic generator with a lot of approximation 
input data : [WSON, U3X, 5x6x0.8mm, 8, , C, C04-00210C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,6.0,0.8], center=false);
