/* Warning, this is a very basic generator with a lot of approximation 
input data : [TDFN, H9A, 2.5x2.0x1.15mm, 10, , A, C04-01061A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.5,2.0,1.15], center=false);
