/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 9LX, 5.5x5.5x1.1mm, 82, , A, C04-00492A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.5,5.5,1.1], center=false);
