/* Warning, this is a very basic generator with a lot of approximation 
input data : [LQFP, H8X, 20x20x1.4mm, 144, , D, C04-00044D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([20.0,20.0,1.4], center=false);
