/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFBGA, 4GX, 7x7x1mm, 64, , A, C04-00370A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,7.0,1.0], center=false);
