/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, 3TW, 3x4.5x1.0mm, 16, , B, C04-00572B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,4.5,1.0], center=false);
