/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, KMX, 5.5x4.5x1.1mm, 60, , A, C04-00464A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.5,4.5,1.1], center=false);
