/* Warning, this is a very basic generator with a lot of approximation 
input data : [BBGA, 7JC, 45x45x3.90mm, 1894, , A, C04-25090A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([45.0,45.0,3.9], center=false);
