/* Warning, this is a very basic generator with a lot of approximation 
input data : [TOLL, 8UW, 9.9x11.68x2.40mm, 8, , A, C04-00673A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.9,11.68,2.4], center=false);
