/* Warning, this is a very basic generator with a lot of approximation 
input data : [WSON, S9X, 6x8x0.8mm, 8, , B, C04-00172B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,8.0,0.8], center=false);
