/* Warning, this is a very basic generator with a lot of approximation 
input data : [CDFP, SGC, 6.48x6.48mm, 10, , B, C04-25641B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.48,6.48,1.0], center=false);
