/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFBGA, A6B, 8x8x1.4mm, 64, , A, C04-21114A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,8.0,1.4], center=false);
