/* Warning, this is a very basic generator with a lot of approximation 
input data : [WQFN, SMC, 6x7x0.7mm, 39, , A, C04-25649A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,7.0,0.7], center=false);
