/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 9TX, 8x10x1.2mm, 48, , A, C04-00170A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,10.0,1.2], center=false);
