/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, FLB, 2.639x3.154x0.355mm, 8, , B, C04-21241B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.639,3.154,0.355], center=false);
