/* Warning, this is a very basic generator with a lot of approximation 
input data : [UPQFN, 6EW, 5x5x0.55mm, 40, , B, C04-00621B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,5.0,0.55], center=false);
