/* Warning, this is a very basic generator with a lot of approximation 
input data : [UQFN, GNX, 4x4x0.55mm, 20, , A, C04-00252A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,0.55], center=false);
