/* Warning, this is a very basic generator with a lot of approximation 
input data : [HBGA, 8LW, 52.5x52.5x4.2mm, 3727, , C, C04-00665C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([52.5,52.5,4.2], center=false);
