/* Warning, this is a very basic generator with a lot of approximation 
input data : [MQFP, ZBX, 28x28x3.4mm, 256, , A, C04-00133A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([28.0,28.0,3.4], center=false);
