/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, Q2B, 2x2x0.6mm, 8, , B, C04-21353B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.6], center=false);
