/* Warning, this is a very basic generator with a lot of approximation 
input data : [UQFN, 2VX, 1.3x1.8x0.6mm, 10, , A, C04-00386A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.3,1.8,0.6], center=false);
