/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, NNA, 4.5x4.5x0.9mm, 36, , A, C04-01036A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.5,4.5,0.9], center=false);
