/* Warning, this is a very basic generator with a lot of approximation 
input data : [BBGA, JXC, 40x40x4.03mm, 1517, , A, C04-25515A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([40.0,40.0,4.03], center=false);
