/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, EJB, 0.847x1.096x0.330mm, 5, , A, C04-21208A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([0.847,1.096,0.33], center=false);
