/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, 3BW, 13.4x18.7x2.8mm, 30, , D, C04-10055D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([13.4,18.7,2.8], center=false);
