/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, HXA, 1.3x2.0x0.6mm, 6, , D, C04-01245D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.3,2.0,0.6], center=false);
