/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, LDB, 22.428x14.732mm, 36, , B, C04-21306B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([22.428,14.732,1.0], center=false);
