/* Warning, this is a very basic generator with a lot of approximation 
input data : [B2BGA, NHC, 31x31x3.25mm, 896, , A, C04-25476A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([31.0,31.0,3.25], center=false);
