/* Warning, this is a very basic generator with a lot of approximation 
input data : [FSTQFP, 3HC, 24x24mm, 302, , A, C04-25027A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([24.0,24.0,1.0], center=false);
