/* Warning, this is a very basic generator with a lot of approximation 
input data : [HSBGA, 9MX, 14x14x1.7mm, 256, , A, C04-00324A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,14.0,1.7], center=false);
