/* Warning, this is a very basic generator with a lot of approximation 
input data : [CSP, 75X, 5.29x5.30x1.02mm, 42, , B, C04-00533B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.29,5.3,1.02], center=false);
