/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 4LX, 11x11x1.19mm, 176, , A, C04-00481A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,1.19], center=false);
