/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFBGA, E8B, 1.5x2x0.85mm, 8, , A, C04-21198A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.5,2.0,0.85], center=false);
