/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, HEA, 1.2x1.2x0.6mm, 4, , A, C04-01044A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.2,1.2,0.6], center=false);
