/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFBGA, E9B, 2.35x3.73x1mm, 8, , A, C04-21199A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.35,3.73,1.0], center=false);
