/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, QVX, 3x3x1.0mm, 16, , A, C04-00196A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.0,3.0,1.0], center=false);
