/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, HEB, 8x8x1.2mm, 120, , C, C04-21465C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([8.0,8.0,1.2], center=false);
