/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, FQB, 2.821x2.529x0.483mm, 35, , A, C04-21245A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.821,2.529,0.483], center=false);
