/* Warning, this is a very basic generator with a lot of approximation 
input data : [QFN, 8EX, 4x4x0.9mm, 16, , B, C04-00259B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,0.9], center=false);
