/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, AHA, 12x12x1.2mm, 132, , C, C04-01193C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,12.0,1.2], center=false);
