/* Warning, this is a very basic generator with a lot of approximation 
input data : [QFN, NTA, 10x6x2.1mm, 54, , A, C04-01086A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,6.0,2.1], center=false);
