/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, HKB, 1.7x3.0x0.5675mm, 18, , A, C04-06037A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.7,3.0,0.5675], center=false);
