/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFLGA, JUC, 11x11x0.9mm, 80, , C, C04-25351C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,0.9], center=false);
