/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, Q7B, 2.x3x0.9mm, 8, , A, C04-21357A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,3.0,0.9], center=false);
