/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, FEB, 2.206x3.47x0.534mm, 8, , A, C04-21235A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.206,3.47,0.534], center=false);
