/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 2RW, 7x7x0.95mm, 84, , A, C04-00551A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,7.0,0.95], center=false);
