/* Warning, this is a very basic generator with a lot of approximation 
input data : [TQFP, 4KB, 16x16x1mm, 144, , A, C04-21546A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([16.0,16.0,1.0], center=false);
