/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, HLB, 2.22x2.92x0.45mm, 48, , A, C04-06038A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.22,2.92,0.45], center=false);
