/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, AKA, 6x6x1.2mm, 60, , A, C04-01277A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.0,6.0,1.2], center=false);
