/* Warning, this is a very basic generator with a lot of approximation 
input data : [WQFN, 6PX, 5x5x0.8mm, 40, , A, C04-00306A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,5.0,0.8], center=false);
