/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, N3A, 3.5x3.5x0.75mm, 20, , A, C04-01033A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.5,3.5,0.75], center=false);
