/* Warning, this is a very basic generator with a lot of approximation 
input data : [TQFP, 8YX, 20x20x1.0mm, 144, , A, C04-00510A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([20.0,20.0,1.0], center=false);
