/* Warning, this is a very basic generator with a lot of approximation 
input data : [XFBGA, TZX, 7x7x0.5mm, 144, , A, C04-00337A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,7.0,0.5], center=false);
