/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, FWB, 3.25x3.25x0.589mm, 55, , A, C04-21251A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.25,3.25,0.589], center=false);
