/* Warning, this is a very basic generator with a lot of approximation 
input data : [CABGA, JYX, 5x7x0.98mm, 22, , A, C04-00414A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,7.0,0.98], center=false);
