/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, SQB, 7x7x0.9mm, 32, , B, C04-21417B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,7.0,0.9], center=false);
