/* Warning, this is a very basic generator with a lot of approximation 
input data : [LQFN, LYA, 4x6x1.55mm, 28, , A, C04-01294A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,6.0,1.55], center=false);
