/* Warning, this is a very basic generator with a lot of approximation 
input data : [CDFP, HHB, 7.67x8.41mm, 8, , B, C04-21533B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.67,8.41,1.0], center=false);
