/* Warning, this is a very basic generator with a lot of approximation 
input data : [MFPF, 3XB, 6.485x6.485x2.89mm, 8, , A, C04-21552A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([6.485,6.485,2.89], center=false);
