/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 2GX, 7x7x1.0mm, 56, , B, C04-00234B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,7.0,1.0], center=false);
