/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, PPA, 5x6x0.9mm, 38, , A, C04-01041A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,6.0,0.9], center=false);
