/* Warning, this is a very basic generator with a lot of approximation 
input data : [VFLGA, 3YW, 5x5mm, 24, , A, C04-00577A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,5.0,1.0], center=false);
