/* Warning, this is a very basic generator with a lot of approximation 
input data : [MODULE, 4SW, 15.5x26.8mm, 39, , D, C04-10056D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([15.5,26.8,1.0], center=false);
