/* Warning, this is a very basic generator with a lot of approximation 
input data : [X2DFN, 4AX, 1.5x1.8x0.33mm, 6, , A, C04-00441A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.5,1.8,0.33], center=false);
