/* Warning, this is a very basic generator with a lot of approximation 
input data : [UFBGA, C2B, 7x5x0.65mm, 114, , A, C04-21163A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,5.0,0.65], center=false);
