/* Warning, this is a very basic generator with a lot of approximation 
input data : [PDFN, ASX, 5x6x0.9mm, 8, , B, C04-00188B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,6.0,0.9], center=false);
