/* Warning, this is a very basic generator with a lot of approximation 
input data : [VPQFN, 9GW, 3.5x3.5x0.9mm, 32, , A, C04-00684A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([3.5,3.5,0.9], center=false);
