/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, HRA, 2.5x2.5x0.6mm, 12, , A, C04-01162A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.5,2.5,0.6], center=false);
