/* Warning, this is a very basic generator with a lot of approximation 
input data : [VTLA, 8SX, 9x9x0.9mm, 124, , A, C04-00193A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([9.0,9.0,0.9], center=false);
