/* Warning, this is a very basic generator with a lot of approximation 
input data : [WFBGA, TNX, 11x11x0.8mm, 169, , A, C04-00336A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([11.0,11.0,0.8], center=false);
