/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, FRB, 2.84x2.84x0.29mm, 49, , A, C04-21246A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.84,2.84,0.29], center=false);
