/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 8MX, 15x15x1.19mm, 208, , A, C04-00516A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([15.0,15.0,1.19], center=false);
