/* Warning, this is a very basic generator with a lot of approximation 
input data : [UQFN, JQX, 4x4x0.5mm, 16, , A, C04-00257A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,0.5], center=false);
