/* Warning, this is a very basic generator with a lot of approximation 
input data : [LFLGA, DAB, 4.5x5.5x1.4mm, 49, , A, C04-21477A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.5,5.5,1.4], center=false);
