/* Warning, this is a very basic generator with a lot of approximation 
input data : [TO-263, 6FW, 10.35x8.8mm, 2, , B, C04-00618B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.35,8.8,1.0], center=false);
