/* Warning, this is a very basic generator with a lot of approximation 
input data : [B1BGA, NGC, 31x31x2.70mm, 896, , A, C04-25475A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([31.0,31.0,2.7], center=false);
