/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 7GX, 10x10x1.0mm, 169, , D, C04-00377D]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([10.0,10.0,1.0], center=false);
