/* Warning, this is a very basic generator with a lot of approximation 
input data : [WDFN, USX, 4x4x0.8mm, 10, , A, C04-00293A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([4.0,4.0,0.8], center=false);
