/* Warning, this is a very basic generator with a lot of approximation 
input data : [TFBGA, 5MX, 14x14x1.19mm, 176, , A, C04-00515A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([14.0,14.0,1.19], center=false);
