/* Warning, this is a very basic generator with a lot of approximation 
input data : [WQFN, 7PX, 7x7x0.8mm, 44, , A, C04-00307A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,7.0,0.8], center=false);
