/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, 2ZX, 12x12x0.9mm, 108, , A, C04-00478A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,12.0,0.9], center=false);
