/* Warning, this is a very basic generator with a lot of approximation 
input data : [UDFN, HDA, 1.25x1.25mm, 4, , A, C04-01150A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.25,1.25,1.0], center=false);
