/* Warning, this is a very basic generator with a lot of approximation 
input data : [B2QFN, M7A, 12x12x4mm, 64, , A, C04-01058A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,12.0,4.0], center=false);
