/* Warning, this is a very basic generator with a lot of approximation 
input data : [WDFN, RWX, 2x2x0.8mm, 8, , C, C04-00261C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:48 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([2.0,2.0,0.8], center=false);
