/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, SPC, 23x23x2.23mm, 784, , A, C04-25664A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([23.0,23.0,2.23], center=false);
