/* Warning, this is a very basic generator with a lot of approximation 
input data : [XSFN, QJB, 5x3.5x0.4mm, 2, , A, C04-21368A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([5.0,3.5,0.4], center=false);
