/* Warning, this is a very basic generator with a lot of approximation 
input data : [WLCSP, F4B, 1.555x1.403x0.538mm, 12, , A, C04-21226A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.555,1.403,0.538], center=false);
