/* Warning, this is a very basic generator with a lot of approximation 
input data : [PLCC, XPX, 29.3x29.3x4.4mm, 84, , C, C04-00093C]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 22 13:34:47 CET 2026
*/
D1=29.3;
E1=29.3;
A=4.4;
LINE1="M PIC32";
LINE2="XXXXXX";
LINE3="XXXXXX";
LINE4="IIIIII";
LINE5="YYWWNNN";

//body
    module C04_00093C(      LINE1="M PIC32",
			LINE2="CPNCPN",
			LINE3="CPNCPN",
			LINE4="IIIIII",
			LINE5="YYWWNNN")
{
color("black")
translate([0,0,0])
cube([29.3,29.3,4.4], center=false); 
	color("white")
	scale([1,1,0.1])
	translate([D1/2,E1-1*E1/7,A*10+0.5]) 
	     linear_extrude(height = 3, center = true, convexity = 10, twist = 0) 
	{
        translate([0.3-D1/2,0,0])
      text(".", size=12.557142857142859, font="Liberation Serif",  valign ="left", halign ="left");
     
      translate([0,-1*E1/7,0]) 
	text(LINE1, size=0.9*E1/7, font="Liberation Serif",  valign ="left", halign ="center");

   translate([0,-2*E1/7,0]) 
	text(LINE2, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
 translate([0,-3*E1/7,0]) 
	text(LINE3, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
   translate([0,-4*E1/7,0]) 
	text(LINE4, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");  
   translate([0,-5*E1/7,0]) 
	text(LINE5, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");     
	}
  
  }
 
      if(demo==undef)
          
      	C04_00093C();

