/* Warning, this is a very basic generator with a lot of approximation 
input data : [VQFN, PXA, 7X7X0.9mm, 48, , F, C04-01263F]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([7.0,7.0,0.9], center=false);
