/* Warning, this is a very basic generator with a lot of approximation 
input data : [VDFN, 8JW, 1.6x1.4x0.9mm, 8, , A, C04-00663A]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([1.6,1.4,0.9], center=false);
