/* Warning, this is a very basic generator with a lot of approximation 
input data : [FBGA, 6VW, 12x21x1.78mm, 448, , B, C04-00635B]
generated by com.zoubworld.electronics.cad.model3d.Basic
Date : Sun Feb 15 10:50:49 CET 2026
*/

//body
color("black")
translate([0,0,0])
cube([12.0,21.0,1.78], center=false);
