/*32-Lead Very Thin Plastic Quad Flat, No Lead Package (RTB) - 5.0x5.0 mm Body [VQFN]
With 3.7x3.7 mm Exposed Pad and Stepped Wettable Flanks;
generated by com.zoubworld.electronics.cad.model3d.QFN32
Date : Sun Feb 22 22:49:45 CET 2026
*/
N = 32.0 ;
A1 = 0.05 ;
A4 = 0.19 ;
E = 5.0 ;
E2 = 3.7 ;
A = 1.0 ;
D = 5.0 ;
D2 = 3.7 ;
L = 0.45 ;
A3 = 0.203 ;
K = 0.2 ;
e = 0.5 ;
b = 0.3 ;
D3 = 0.085 ;
LINE1="M PIC32";
LINE2="XXXXXX";
LINE3="XXXXXX";
LINE4="IIIIII";
LINE5="YYWWNNN";
$fn =64;

//body
color("black")
translate([0,0,A1])
cube([D,E,A-A1], center=false);

// pad
for (i = [-N/4/2 : 1 : N/4/2-1])
color("grey")
translate([D/2-b/2+e/2+e*i,0,0])
cube([b,L,A3], center=false);

for (i = [-N/4/2 : 1 : N/4/2-1])
color("grey")
translate([D/2-b/2+e/2+e*i,E-L,0])
cube([b,L,A3], center=false);


for (i = [-N/4/2 : 1 : N/4/2-1])
color("grey")
translate([0,E/2-b/2+e/2+e*i,0])
cube([L,b,A3], center=false);



for (i = [-N/4/2 : 1 : N/4/2-1])
color("grey")
translate([D-L,E/2-b/2+e/2+e*i,0])
cube([L,b,A3], center=false);

//expose pad
color("grey")
translate([D/2-D2/2,E/2-E2/2,0])
cube([D2,E2,A3], center=false);

color("white")
translate([0.5,0.5,A3])
cylinder(A-A3/2,r=0.25,center=false);
E1=E;

D1=D;
	color("white")
	scale([1,1,0.1])
	translate([-D1+D,E/2,A*10+0.5]) 
 rotate([0,0,90])
	     linear_extrude(height = 3, center = true, convexity = 10, twist = 0) 
	{
        translate([0.3-D1/2,0,0])
      text(".", size=2.142857142857143, font="Liberation Serif",  valign ="left", halign ="left");
     
      translate([0,-1*E1/7,0]) 
	text(LINE1, size=0.9*E1/7, font="Liberation Serif",  valign ="left", halign ="center");

   translate([0,-2*E1/7,0]) 
	text(LINE2, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
 translate([0,-3*E1/7,0]) 
	text(LINE3, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
   translate([0,-4*E1/7,0]) 
	text(LINE4, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");  
   translate([0,-5*E1/7,0]) 
	text(LINE5, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");     
	}
