/*64-Lead Plastic Thin Quad Flatpack - 12.0x12.0 mm Body [TQFP]

generated by com.zoubworld.electronics.cad.model3d.TQFP64
Date : Sun Feb 22 22:49:45 CET 2026
*/
L1 = 1.0 ;
A = 1.2 ;
b = 0.27 ;
D = 12.0 ;
A1 = 0.15 ;
theta = 7.0 ;
D1 = 10.0 ;
E1 = 10.0 ;
L = 0.75 ;
E = 12.0 ;
N = 64.0 ;
A3 = 1.05 ;
c = 0.2 ;
e = 0.5 ;
LINE1="M PIC32";
LINE2="XXXXXX";
LINE3="XXXXXX";
LINE4="IIIII";
LINE5="YYWWNNN";
$fn =64;

/**
b=pin_width
L=Foot Length
L1=Footprint
theta=Foot Angle
A2= Molded Package Thickness
*/
module pin_TQFP(x=0,y=0,L1=1, L=0.6, c=0.2, b=0.5, theta=3.5, A2=1){
    translate([x,y, 0])
        rotate([90,0,00])
        translate([L1-L,c*1.5, 0])
        {
        translate([-L1/2+L/2,c, 0])
        rotate([90,0,90])
     linear_extrude(height = L1-L, center = true, convexity = 90, twist = -0)
     square([c,b],center=true);
     
        rotate_extrude(angle=90, convexity=10)
    translate([c, 0]) square([c,b],center=true);

    rotate([0,0,180])
     translate([-c*2,0, 0])
         rotate_extrude(angle=90, convexity=10)
    translate([c, 0]) square([c,b],center=true);

    
     translate([L-c,-c-c*sin(theta)*2, 0])
        rotate([90,0,90-theta])
     linear_extrude(height = L-c, center = true, convexity = 90, twist = -0)
     square([c,b],center=true);
   }
}


//body
color("black")
translate([D/2-D1/2,E/2-E1/2,A1])
cube([D1,E1,A-A1], center=false);

// pad
for (i = [-N/4/2 : 1 : N/4/2-1])
color("grey")
translate([D/2-b/2+e/2+e*i,0,0])
translate([0,L1,c])
rotate([0,0,-90])
pin_TQFP(0,0,L1, L, c, b, theta, A2);

for (i = [-N/4/2 : 1 : N/4/2-1])
color("grey")
translate([D/2-b/2+e/2+e*i,E-L,0])
translate([0,-L1/2+b/2,c])
rotate([0,0,90])

pin_TQFP(0,0,L1, L, c, b, theta, A2);

for (i = [-N/4/2 : 1 : N/4/2-1])
color("grey")
translate([0,E/2-b/2+e/2+e*i,0])
rotate([0,0,180])
translate([-L1,0,c])
pin_TQFP(0,0,L1, L, c, b, theta, A2);

for (i = [-N/4/2 : 1 : N/4/2-1])
color("grey")
translate([D-L,E/2-b/2+e/2+e*i,c])
 
pin_TQFP(0,0,L1, L, c, b, theta, A2);
/*
//expose pad
color("grey")
translate([D/2-D2/2,E/2-E2/2,0])
cube([D2,E2,A3], center=false);
*/
color("white")
translate([D/2-D1/2+0.5,E/2-E1/2+0.5,c])
cylinder(A-c/2,r=0.25,center=false);

	color("white")
	scale([1,1,0.1])
	translate([-D1+D,E/2,A*10+0.5]) 
 rotate([0,0,90])
	     linear_extrude(height = 3, center = true, convexity = 10, twist = 0) 
	{
        translate([0.3-D1/2,0,0])
      text(".", size=5.142857142857143, font="Liberation Serif",  valign ="left", halign ="left");
     
      translate([0,-1*E1/7,0]) 
	text(LINE1, size=0.9*E1/7, font="Liberation Serif",  valign ="left", halign ="center");

   translate([0,-2*E1/7,0]) 
	text(LINE2, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
 translate([0,-3*E1/7,0]) 
	text(LINE3, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");
   translate([0,-4*E1/7,0]) 
	text(LINE4, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");  
   translate([0,-5*E1/7,0]) 
	text(LINE5, size=0.5*E1/7, font="Liberation Serif",  valign ="left", halign ="center");     
	}
